/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'patientId' : string,
  'date' : string,
  'visitType' : string,
  'notes' : string,
}
export interface Case {
  'id' : string,
  'pastHistory' : string,
  'patientId' : string,
  'year' : bigint,
  'personalHistory' : string,
  'physicalGenerals' : string,
  'history' : string,
  'examination' : string,
  'totality' : string,
  'miasmaticAnalysis' : string,
  'mentalGenerals' : string,
  'familyHistory' : string,
  'followUps' : Array<FollowUp>,
  'repertoiralFindings' : string,
  'prescriptions' : Array<Prescription>,
  'investigations' : string,
  'chiefComplaint' : string,
}
export interface FollowUp {
  'visitNumber' : bigint,
  'prescription' : [] | [Prescription],
  'date' : string,
  'feedback' : string,
  'symptoms' : string,
  'changes' : string,
  'observations' : string,
}
export interface Memo { 'id' : string, 'content' : string, 'date' : string }
export interface Patient {
  'id' : string,
  'age' : bigint,
  'sex' : string,
  'occupation' : string,
  'contact' : string,
  'name' : string,
  'year' : bigint,
  'address' : string,
  'registrationDate' : string,
  'religion' : string,
  'maritalStatus' : string,
}
export interface Prescription {
  'remedy' : string,
  'duration' : string,
  'dosage' : string,
  'date' : string,
  'instructions' : string,
  'potency' : string,
  'frequency' : string,
}
export interface Remedy {
  'rubrics' : string,
  'name' : string,
  'keynotes' : string,
  'synopticKeyHighlights' : string,
  'abbreviation' : string,
  'clinicalIndications' : string,
  'materiaMedicaSummary' : string,
  'relationships' : RemedyRelationships,
  'miasmaticClassification' : string,
}
export interface RemedyRelationships {
  'antidotes' : string,
  'inimical' : string,
  'complementary' : string,
  'followsWell' : string,
  'followedBy' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'specialization' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAppointment' : ActorMethod<[Appointment], undefined>,
  'addMemo' : ActorMethod<[Memo], undefined>,
  'addRemedy' : ActorMethod<[Remedy], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCase' : ActorMethod<[Case], undefined>,
  'deleteAppointment' : ActorMethod<[string], undefined>,
  'deleteCase' : ActorMethod<[string], undefined>,
  'deleteMemo' : ActorMethod<[string], undefined>,
  'deletePatient' : ActorMethod<[string], undefined>,
  'deleteRemedy' : ActorMethod<[string], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllMemos' : ActorMethod<[], Array<Memo>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAllRemedies' : ActorMethod<[], Array<Remedy>>,
  'getAppointment' : ActorMethod<[string], Appointment>,
  'getAppointmentsByDate' : ActorMethod<[string], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCase' : ActorMethod<[string], Case>,
  'getCasesByPatient' : ActorMethod<[string], Array<Case>>,
  'getMemo' : ActorMethod<[string], Memo>,
  'getPatient' : ActorMethod<[string], Patient>,
  'getRemedy' : ActorMethod<[string], Remedy>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerPatient' : ActorMethod<[Patient], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPatientsByName' : ActorMethod<[string], Array<Patient>>,
  'searchRemediesByName' : ActorMethod<[string], Array<Remedy>>,
  'updateAppointment' : ActorMethod<[string, Appointment], undefined>,
  'updateCase' : ActorMethod<[string, Case], undefined>,
  'updateMemo' : ActorMethod<[string, Memo], undefined>,
  'updatePatient' : ActorMethod<[string, Patient], undefined>,
  'updateRemedy' : ActorMethod<[string, Remedy], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];