/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'patientId' : IDL.Text,
  'date' : IDL.Text,
  'visitType' : IDL.Text,
  'notes' : IDL.Text,
});
export const Memo = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
});
export const RemedyRelationships = IDL.Record({
  'antidotes' : IDL.Text,
  'inimical' : IDL.Text,
  'complementary' : IDL.Text,
  'followsWell' : IDL.Text,
  'followedBy' : IDL.Text,
});
export const Remedy = IDL.Record({
  'rubrics' : IDL.Text,
  'name' : IDL.Text,
  'keynotes' : IDL.Text,
  'synopticKeyHighlights' : IDL.Text,
  'abbreviation' : IDL.Text,
  'clinicalIndications' : IDL.Text,
  'materiaMedicaSummary' : IDL.Text,
  'relationships' : RemedyRelationships,
  'miasmaticClassification' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Prescription = IDL.Record({
  'remedy' : IDL.Text,
  'duration' : IDL.Text,
  'dosage' : IDL.Text,
  'date' : IDL.Text,
  'instructions' : IDL.Text,
  'potency' : IDL.Text,
  'frequency' : IDL.Text,
});
export const FollowUp = IDL.Record({
  'visitNumber' : IDL.Nat,
  'prescription' : IDL.Opt(Prescription),
  'date' : IDL.Text,
  'feedback' : IDL.Text,
  'symptoms' : IDL.Text,
  'changes' : IDL.Text,
  'observations' : IDL.Text,
});
export const Case = IDL.Record({
  'id' : IDL.Text,
  'pastHistory' : IDL.Text,
  'patientId' : IDL.Text,
  'year' : IDL.Nat,
  'personalHistory' : IDL.Text,
  'physicalGenerals' : IDL.Text,
  'history' : IDL.Text,
  'examination' : IDL.Text,
  'totality' : IDL.Text,
  'miasmaticAnalysis' : IDL.Text,
  'mentalGenerals' : IDL.Text,
  'familyHistory' : IDL.Text,
  'followUps' : IDL.Vec(FollowUp),
  'repertoiralFindings' : IDL.Text,
  'prescriptions' : IDL.Vec(Prescription),
  'investigations' : IDL.Text,
  'chiefComplaint' : IDL.Text,
});
export const Patient = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'sex' : IDL.Text,
  'occupation' : IDL.Text,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'address' : IDL.Text,
  'registrationDate' : IDL.Text,
  'religion' : IDL.Text,
  'maritalStatus' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'specialization' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAppointment' : IDL.Func([Appointment], [], []),
  'addMemo' : IDL.Func([Memo], [], []),
  'addRemedy' : IDL.Func([Remedy], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCase' : IDL.Func([Case], [], []),
  'deleteAppointment' : IDL.Func([IDL.Text], [], []),
  'deleteCase' : IDL.Func([IDL.Text], [], []),
  'deleteMemo' : IDL.Func([IDL.Text], [], []),
  'deletePatient' : IDL.Func([IDL.Text], [], []),
  'deleteRemedy' : IDL.Func([IDL.Text], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllMemos' : IDL.Func([], [IDL.Vec(Memo)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAllRemedies' : IDL.Func([], [IDL.Vec(Remedy)], ['query']),
  'getAppointment' : IDL.Func([IDL.Text], [Appointment], ['query']),
  'getAppointmentsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCase' : IDL.Func([IDL.Text], [Case], ['query']),
  'getCasesByPatient' : IDL.Func([IDL.Text], [IDL.Vec(Case)], ['query']),
  'getMemo' : IDL.Func([IDL.Text], [Memo], ['query']),
  'getPatient' : IDL.Func([IDL.Text], [Patient], ['query']),
  'getRemedy' : IDL.Func([IDL.Text], [Remedy], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerPatient' : IDL.Func([Patient], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPatientsByName' : IDL.Func([IDL.Text], [IDL.Vec(Patient)], ['query']),
  'searchRemediesByName' : IDL.Func([IDL.Text], [IDL.Vec(Remedy)], ['query']),
  'updateAppointment' : IDL.Func([IDL.Text, Appointment], [], []),
  'updateCase' : IDL.Func([IDL.Text, Case], [], []),
  'updateMemo' : IDL.Func([IDL.Text, Memo], [], []),
  'updatePatient' : IDL.Func([IDL.Text, Patient], [], []),
  'updateRemedy' : IDL.Func([IDL.Text, Remedy], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'patientId' : IDL.Text,
    'date' : IDL.Text,
    'visitType' : IDL.Text,
    'notes' : IDL.Text,
  });
  const Memo = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
  });
  const RemedyRelationships = IDL.Record({
    'antidotes' : IDL.Text,
    'inimical' : IDL.Text,
    'complementary' : IDL.Text,
    'followsWell' : IDL.Text,
    'followedBy' : IDL.Text,
  });
  const Remedy = IDL.Record({
    'rubrics' : IDL.Text,
    'name' : IDL.Text,
    'keynotes' : IDL.Text,
    'synopticKeyHighlights' : IDL.Text,
    'abbreviation' : IDL.Text,
    'clinicalIndications' : IDL.Text,
    'materiaMedicaSummary' : IDL.Text,
    'relationships' : RemedyRelationships,
    'miasmaticClassification' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Prescription = IDL.Record({
    'remedy' : IDL.Text,
    'duration' : IDL.Text,
    'dosage' : IDL.Text,
    'date' : IDL.Text,
    'instructions' : IDL.Text,
    'potency' : IDL.Text,
    'frequency' : IDL.Text,
  });
  const FollowUp = IDL.Record({
    'visitNumber' : IDL.Nat,
    'prescription' : IDL.Opt(Prescription),
    'date' : IDL.Text,
    'feedback' : IDL.Text,
    'symptoms' : IDL.Text,
    'changes' : IDL.Text,
    'observations' : IDL.Text,
  });
  const Case = IDL.Record({
    'id' : IDL.Text,
    'pastHistory' : IDL.Text,
    'patientId' : IDL.Text,
    'year' : IDL.Nat,
    'personalHistory' : IDL.Text,
    'physicalGenerals' : IDL.Text,
    'history' : IDL.Text,
    'examination' : IDL.Text,
    'totality' : IDL.Text,
    'miasmaticAnalysis' : IDL.Text,
    'mentalGenerals' : IDL.Text,
    'familyHistory' : IDL.Text,
    'followUps' : IDL.Vec(FollowUp),
    'repertoiralFindings' : IDL.Text,
    'prescriptions' : IDL.Vec(Prescription),
    'investigations' : IDL.Text,
    'chiefComplaint' : IDL.Text,
  });
  const Patient = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'sex' : IDL.Text,
    'occupation' : IDL.Text,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'address' : IDL.Text,
    'registrationDate' : IDL.Text,
    'religion' : IDL.Text,
    'maritalStatus' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'specialization' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAppointment' : IDL.Func([Appointment], [], []),
    'addMemo' : IDL.Func([Memo], [], []),
    'addRemedy' : IDL.Func([Remedy], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCase' : IDL.Func([Case], [], []),
    'deleteAppointment' : IDL.Func([IDL.Text], [], []),
    'deleteCase' : IDL.Func([IDL.Text], [], []),
    'deleteMemo' : IDL.Func([IDL.Text], [], []),
    'deletePatient' : IDL.Func([IDL.Text], [], []),
    'deleteRemedy' : IDL.Func([IDL.Text], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllMemos' : IDL.Func([], [IDL.Vec(Memo)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAllRemedies' : IDL.Func([], [IDL.Vec(Remedy)], ['query']),
    'getAppointment' : IDL.Func([IDL.Text], [Appointment], ['query']),
    'getAppointmentsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCase' : IDL.Func([IDL.Text], [Case], ['query']),
    'getCasesByPatient' : IDL.Func([IDL.Text], [IDL.Vec(Case)], ['query']),
    'getMemo' : IDL.Func([IDL.Text], [Memo], ['query']),
    'getPatient' : IDL.Func([IDL.Text], [Patient], ['query']),
    'getRemedy' : IDL.Func([IDL.Text], [Remedy], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerPatient' : IDL.Func([Patient], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPatientsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Patient)],
        ['query'],
      ),
    'searchRemediesByName' : IDL.Func([IDL.Text], [IDL.Vec(Remedy)], ['query']),
    'updateAppointment' : IDL.Func([IDL.Text, Appointment], [], []),
    'updateCase' : IDL.Func([IDL.Text, Case], [], []),
    'updateMemo' : IDL.Func([IDL.Text, Memo], [], []),
    'updatePatient' : IDL.Func([IDL.Text, Patient], [], []),
    'updateRemedy' : IDL.Func([IDL.Text, Remedy], [], []),
  });
};

export const init = ({ IDL }) => { return []; };