/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'status' : string,
  'date' : string,
  'time' : string,
  'patientName' : string,
  'reason' : string,
}
export interface CaseSheet {
  'id' : string,
  'hpi' : string,
  'pastHistory' : string,
  'patientId' : string,
  'createdAt' : bigint,
  'year' : bigint,
  'personalHistory' : string,
  'physicalGenerals' : string,
  'examinationFindings' : string,
  'totality' : string,
  'miasmaticAnalysis' : string,
  'updatedAt' : bigint,
  'mentalGenerals' : string,
  'familyHistory' : string,
  'repertorialFindings' : string,
  'investigations' : string,
  'chiefComplaint' : string,
}
export interface FollowUp {
  'id' : string,
  'rows' : string,
  'caseSheetId' : string,
}
export interface Memo {
  'id' : string,
  'content' : string,
  'createdAt' : bigint,
}
export interface Patient {
  'id' : string,
  'age' : bigint,
  'sex' : string,
  'occupation' : string,
  'contact' : string,
  'name' : string,
  'address' : string,
  'registrationYear' : bigint,
}
export interface Prescription {
  'id' : string,
  'rows' : string,
  'caseSheetId' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'specialization' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppointment' : ActorMethod<[Appointment], string>,
  'createCaseSheet' : ActorMethod<[CaseSheet], string>,
  'createFollowUp' : ActorMethod<[FollowUp], string>,
  'createMemo' : ActorMethod<[Memo], string>,
  'createPatient' : ActorMethod<[Patient], string>,
  'createPrescription' : ActorMethod<[Prescription], string>,
  'deleteAppointment' : ActorMethod<[string], undefined>,
  'deleteCaseSheet' : ActorMethod<[string], undefined>,
  'deleteFollowUp' : ActorMethod<[string], undefined>,
  'deleteMemo' : ActorMethod<[string], undefined>,
  'deletePatient' : ActorMethod<[string], undefined>,
  'deletePrescription' : ActorMethod<[string], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllMemos' : ActorMethod<[], Array<Memo>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAppointment' : ActorMethod<[string], Appointment>,
  'getAppointmentsByDate' : ActorMethod<[string], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaseSheet' : ActorMethod<[string], CaseSheet>,
  'getCaseSheetsByPatient' : ActorMethod<[string], Array<CaseSheet>>,
  'getFollowUp' : ActorMethod<[string], FollowUp>,
  'getFollowUpsByCaseSheet' : ActorMethod<[string], Array<FollowUp>>,
  'getPatient' : ActorMethod<[string], Patient>,
  'getPatientsByYear' : ActorMethod<[bigint], Array<Patient>>,
  'getPrescription' : ActorMethod<[string], Prescription>,
  'getPrescriptionsByCaseSheet' : ActorMethod<[string], Array<Prescription>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppointment' : ActorMethod<[string, Appointment], undefined>,
  'updateCaseSheet' : ActorMethod<[string, CaseSheet], undefined>,
  'updateFollowUp' : ActorMethod<[string, FollowUp], undefined>,
  'updateMemo' : ActorMethod<[string, Memo], undefined>,
  'updatePatient' : ActorMethod<[string, Patient], undefined>,
  'updatePrescription' : ActorMethod<[string, Prescription], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];