/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'patientName' : IDL.Text,
  'reason' : IDL.Text,
});
export const CaseSheet = IDL.Record({
  'id' : IDL.Text,
  'hpi' : IDL.Text,
  'pastHistory' : IDL.Text,
  'patientId' : IDL.Text,
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
  'personalHistory' : IDL.Text,
  'physicalGenerals' : IDL.Text,
  'examinationFindings' : IDL.Text,
  'totality' : IDL.Text,
  'miasmaticAnalysis' : IDL.Text,
  'updatedAt' : IDL.Int,
  'mentalGenerals' : IDL.Text,
  'familyHistory' : IDL.Text,
  'repertorialFindings' : IDL.Text,
  'investigations' : IDL.Text,
  'chiefComplaint' : IDL.Text,
});
export const FollowUp = IDL.Record({
  'id' : IDL.Text,
  'rows' : IDL.Text,
  'caseSheetId' : IDL.Text,
});
export const Memo = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Patient = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'sex' : IDL.Text,
  'occupation' : IDL.Text,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'registrationYear' : IDL.Nat,
});
export const Prescription = IDL.Record({
  'id' : IDL.Text,
  'rows' : IDL.Text,
  'caseSheetId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'specialization' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppointment' : IDL.Func([Appointment], [IDL.Text], []),
  'createCaseSheet' : IDL.Func([CaseSheet], [IDL.Text], []),
  'createFollowUp' : IDL.Func([FollowUp], [IDL.Text], []),
  'createMemo' : IDL.Func([Memo], [IDL.Text], []),
  'createPatient' : IDL.Func([Patient], [IDL.Text], []),
  'createPrescription' : IDL.Func([Prescription], [IDL.Text], []),
  'deleteAppointment' : IDL.Func([IDL.Text], [], []),
  'deleteCaseSheet' : IDL.Func([IDL.Text], [], []),
  'deleteFollowUp' : IDL.Func([IDL.Text], [], []),
  'deleteMemo' : IDL.Func([IDL.Text], [], []),
  'deletePatient' : IDL.Func([IDL.Text], [], []),
  'deletePrescription' : IDL.Func([IDL.Text], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllMemos' : IDL.Func([], [IDL.Vec(Memo)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAppointment' : IDL.Func([IDL.Text], [Appointment], ['query']),
  'getAppointmentsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaseSheet' : IDL.Func([IDL.Text], [CaseSheet], ['query']),
  'getCaseSheetsByPatient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CaseSheet)],
      ['query'],
    ),
  'getFollowUp' : IDL.Func([IDL.Text], [FollowUp], ['query']),
  'getFollowUpsByCaseSheet' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FollowUp)],
      ['query'],
    ),
  'getPatient' : IDL.Func([IDL.Text], [Patient], ['query']),
  'getPatientsByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Patient)], ['query']),
  'getPrescription' : IDL.Func([IDL.Text], [Prescription], ['query']),
  'getPrescriptionsByCaseSheet' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAppointment' : IDL.Func([IDL.Text, Appointment], [], []),
  'updateCaseSheet' : IDL.Func([IDL.Text, CaseSheet], [], []),
  'updateFollowUp' : IDL.Func([IDL.Text, FollowUp], [], []),
  'updateMemo' : IDL.Func([IDL.Text, Memo], [], []),
  'updatePatient' : IDL.Func([IDL.Text, Patient], [], []),
  'updatePrescription' : IDL.Func([IDL.Text, Prescription], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'patientName' : IDL.Text,
    'reason' : IDL.Text,
  });
  const CaseSheet = IDL.Record({
    'id' : IDL.Text,
    'hpi' : IDL.Text,
    'pastHistory' : IDL.Text,
    'patientId' : IDL.Text,
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
    'personalHistory' : IDL.Text,
    'physicalGenerals' : IDL.Text,
    'examinationFindings' : IDL.Text,
    'totality' : IDL.Text,
    'miasmaticAnalysis' : IDL.Text,
    'updatedAt' : IDL.Int,
    'mentalGenerals' : IDL.Text,
    'familyHistory' : IDL.Text,
    'repertorialFindings' : IDL.Text,
    'investigations' : IDL.Text,
    'chiefComplaint' : IDL.Text,
  });
  const FollowUp = IDL.Record({
    'id' : IDL.Text,
    'rows' : IDL.Text,
    'caseSheetId' : IDL.Text,
  });
  const Memo = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Patient = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'sex' : IDL.Text,
    'occupation' : IDL.Text,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'registrationYear' : IDL.Nat,
  });
  const Prescription = IDL.Record({
    'id' : IDL.Text,
    'rows' : IDL.Text,
    'caseSheetId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'specialization' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppointment' : IDL.Func([Appointment], [IDL.Text], []),
    'createCaseSheet' : IDL.Func([CaseSheet], [IDL.Text], []),
    'createFollowUp' : IDL.Func([FollowUp], [IDL.Text], []),
    'createMemo' : IDL.Func([Memo], [IDL.Text], []),
    'createPatient' : IDL.Func([Patient], [IDL.Text], []),
    'createPrescription' : IDL.Func([Prescription], [IDL.Text], []),
    'deleteAppointment' : IDL.Func([IDL.Text], [], []),
    'deleteCaseSheet' : IDL.Func([IDL.Text], [], []),
    'deleteFollowUp' : IDL.Func([IDL.Text], [], []),
    'deleteMemo' : IDL.Func([IDL.Text], [], []),
    'deletePatient' : IDL.Func([IDL.Text], [], []),
    'deletePrescription' : IDL.Func([IDL.Text], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllMemos' : IDL.Func([], [IDL.Vec(Memo)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAppointment' : IDL.Func([IDL.Text], [Appointment], ['query']),
    'getAppointmentsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaseSheet' : IDL.Func([IDL.Text], [CaseSheet], ['query']),
    'getCaseSheetsByPatient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CaseSheet)],
        ['query'],
      ),
    'getFollowUp' : IDL.Func([IDL.Text], [FollowUp], ['query']),
    'getFollowUpsByCaseSheet' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FollowUp)],
        ['query'],
      ),
    'getPatient' : IDL.Func([IDL.Text], [Patient], ['query']),
    'getPatientsByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Patient)], ['query']),
    'getPrescription' : IDL.Func([IDL.Text], [Prescription], ['query']),
    'getPrescriptionsByCaseSheet' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAppointment' : IDL.Func([IDL.Text, Appointment], [], []),
    'updateCaseSheet' : IDL.Func([IDL.Text, CaseSheet], [], []),
    'updateFollowUp' : IDL.Func([IDL.Text, FollowUp], [], []),
    'updateMemo' : IDL.Func([IDL.Text, Memo], [], []),
    'updatePatient' : IDL.Func([IDL.Text, Patient], [], []),
    'updatePrescription' : IDL.Func([IDL.Text, Prescription], [], []),
  });
};

export const init = ({ IDL }) => { return []; };