/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Remedy {
    rubrics: string;
    name: string;
    keynotes: string;
    synopticKeyHighlights: string;
    abbreviation: string;
    clinicalIndications: string;
    materiaMedicaSummary: string;
    relationships: RemedyRelationships;
    miasmaticClassification: string;
}
export interface Case {
    id: string;
    pastHistory: string;
    patientId: string;
    year: bigint;
    personalHistory: string;
    physicalGenerals: string;
    history: string;
    examination: string;
    totality: string;
    miasmaticAnalysis: string;
    mentalGenerals: string;
    familyHistory: string;
    followUps: Array<FollowUp>;
    repertoiralFindings: string;
    prescriptions: Array<Prescription>;
    investigations: string;
    chiefComplaint: string;
}
export interface Memo {
    id: string;
    content: string;
    date: string;
}
export interface RemedyRelationships {
    antidotes: string;
    inimical: string;
    complementary: string;
    followsWell: string;
    followedBy: string;
}
export interface FollowUp {
    visitNumber: bigint;
    prescription?: Prescription;
    date: string;
    feedback: string;
    symptoms: string;
    changes: string;
    observations: string;
}
export interface Appointment {
    id: string;
    patientId: string;
    date: string;
    visitType: string;
    notes: string;
}
export interface Prescription {
    remedy: string;
    duration: string;
    dosage: string;
    date: string;
    instructions: string;
    potency: string;
    frequency: string;
}
export interface Patient {
    id: string;
    age: bigint;
    sex: string;
    occupation: string;
    contact: string;
    name: string;
    year: bigint;
    address: string;
    registrationDate: string;
    religion: string;
    maritalStatus: string;
}
export interface UserProfile {
    name: string;
    role: string;
    specialization?: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAppointment(appointment: Appointment): Promise<void>;
    addMemo(memo: Memo): Promise<void>;
    addRemedy(remedy: Remedy): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCase(caseData: Case): Promise<void>;
    deleteAppointment(id: string): Promise<void>;
    deleteCase(id: string): Promise<void>;
    deleteMemo(id: string): Promise<void>;
    deletePatient(id: string): Promise<void>;
    deleteRemedy(abbreviation: string): Promise<void>;
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllMemos(): Promise<Array<Memo>>;
    getAllPatients(): Promise<Array<Patient>>;
    getAllRemedies(): Promise<Array<Remedy>>;
    getAppointment(id: string): Promise<Appointment>;
    getAppointmentsByDate(date: string): Promise<Array<Appointment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCase(id: string): Promise<Case>;
    getCasesByPatient(patientId: string): Promise<Array<Case>>;
    getMemo(id: string): Promise<Memo>;
    getPatient(id: string): Promise<Patient>;
    getRemedy(abbreviation: string): Promise<Remedy>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerPatient(patient: Patient): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPatientsByName(name: string): Promise<Array<Patient>>;
    searchRemediesByName(name: string): Promise<Array<Remedy>>;
    updateAppointment(id: string, appointment: Appointment): Promise<void>;
    updateCase(id: string, caseData: Case): Promise<void>;
    updateMemo(id: string, memo: Memo): Promise<void>;
    updatePatient(id: string, patient: Patient): Promise<void>;
    updateRemedy(abbreviation: string, remedy: Remedy): Promise<void>;
}
import type { Case as _Case, FollowUp as _FollowUp, Prescription as _Prescription, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAppointment(arg0: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAppointment(arg0);
            return result;
        }
    }
    async addMemo(arg0: Memo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMemo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMemo(arg0);
            return result;
        }
    }
    async addRemedy(arg0: Remedy): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRemedy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRemedy(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCase(arg0: Case): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCase(to_candid_Case_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCase(to_candid_Case_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAppointment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return result;
        }
    }
    async deleteCase(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCase(arg0);
            return result;
        }
    }
    async deleteMemo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMemo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMemo(arg0);
            return result;
        }
    }
    async deletePatient(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async deleteRemedy(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRemedy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRemedy(arg0);
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return result;
        }
    }
    async getAllMemos(): Promise<Array<Memo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMemos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMemos();
            return result;
        }
    }
    async getAllPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return result;
        }
    }
    async getAllRemedies(): Promise<Array<Remedy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRemedies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRemedies();
            return result;
        }
    }
    async getAppointment(arg0: string): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return result;
        }
    }
    async getAppointmentsByDate(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByDate(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCase(arg0: string): Promise<Case> {
        if (this.processError) {
            try {
                const result = await this.actor.getCase(arg0);
                return from_candid_Case_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCase(arg0);
            return from_candid_Case_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCasesByPatient(arg0: string): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCasesByPatient(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCasesByPatient(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemo(arg0: string): Promise<Memo> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemo(arg0);
            return result;
        }
    }
    async getPatient(arg0: string): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return result;
        }
    }
    async getRemedy(arg0: string): Promise<Remedy> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemedy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemedy(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerPatient(arg0: Patient): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPatient(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchPatientsByName(arg0: string): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPatientsByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPatientsByName(arg0);
            return result;
        }
    }
    async searchRemediesByName(arg0: string): Promise<Array<Remedy>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRemediesByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRemediesByName(arg0);
            return result;
        }
    }
    async updateAppointment(arg0: string, arg1: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointment(arg0, arg1);
            return result;
        }
    }
    async updateCase(arg0: string, arg1: Case): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCase(arg0, to_candid_Case_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCase(arg0, to_candid_Case_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMemo(arg0: string, arg1: Memo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemo(arg0, arg1);
            return result;
        }
    }
    async updatePatient(arg0: string, arg1: Patient): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, arg1);
            return result;
        }
    }
    async updateRemedy(arg0: string, arg1: Remedy): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRemedy(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRemedy(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Case_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Case): Case {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_FollowUp_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUp): FollowUp {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Prescription]): Prescription | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    specialization: [] | [string];
}): {
    name: string;
    role: string;
    specialization?: string;
} {
    return {
        name: value.name,
        role: value.role,
        specialization: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.specialization))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    pastHistory: string;
    patientId: string;
    year: bigint;
    personalHistory: string;
    physicalGenerals: string;
    history: string;
    examination: string;
    totality: string;
    miasmaticAnalysis: string;
    mentalGenerals: string;
    familyHistory: string;
    followUps: Array<_FollowUp>;
    repertoiralFindings: string;
    prescriptions: Array<_Prescription>;
    investigations: string;
    chiefComplaint: string;
}): {
    id: string;
    pastHistory: string;
    patientId: string;
    year: bigint;
    personalHistory: string;
    physicalGenerals: string;
    history: string;
    examination: string;
    totality: string;
    miasmaticAnalysis: string;
    mentalGenerals: string;
    familyHistory: string;
    followUps: Array<FollowUp>;
    repertoiralFindings: string;
    prescriptions: Array<Prescription>;
    investigations: string;
    chiefComplaint: string;
} {
    return {
        id: value.id,
        pastHistory: value.pastHistory,
        patientId: value.patientId,
        year: value.year,
        personalHistory: value.personalHistory,
        physicalGenerals: value.physicalGenerals,
        history: value.history,
        examination: value.examination,
        totality: value.totality,
        miasmaticAnalysis: value.miasmaticAnalysis,
        mentalGenerals: value.mentalGenerals,
        familyHistory: value.familyHistory,
        followUps: from_candid_vec_n16(_uploadFile, _downloadFile, value.followUps),
        repertoiralFindings: value.repertoiralFindings,
        prescriptions: value.prescriptions,
        investigations: value.investigations,
        chiefComplaint: value.chiefComplaint
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    visitNumber: bigint;
    prescription: [] | [_Prescription];
    date: string;
    feedback: string;
    symptoms: string;
    changes: string;
    observations: string;
}): {
    visitNumber: bigint;
    prescription?: Prescription;
    date: string;
    feedback: string;
    symptoms: string;
    changes: string;
    observations: string;
} {
    return {
        visitNumber: value.visitNumber,
        prescription: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.prescription)),
        date: value.date,
        feedback: value.feedback,
        symptoms: value.symptoms,
        changes: value.changes,
        observations: value.observations
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FollowUp>): Array<FollowUp> {
    return value.map((x)=>from_candid_FollowUp_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Case>): Array<Case> {
    return value.map((x)=>from_candid_Case_n14(_uploadFile, _downloadFile, x));
}
function to_candid_Case_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Case): _Case {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FollowUp_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FollowUp): _FollowUp {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    specialization?: string;
}): {
    name: string;
    role: string;
    specialization: [] | [string];
} {
    return {
        name: value.name,
        role: value.role,
        specialization: value.specialization ? candid_some(value.specialization) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    pastHistory: string;
    patientId: string;
    year: bigint;
    personalHistory: string;
    physicalGenerals: string;
    history: string;
    examination: string;
    totality: string;
    miasmaticAnalysis: string;
    mentalGenerals: string;
    familyHistory: string;
    followUps: Array<FollowUp>;
    repertoiralFindings: string;
    prescriptions: Array<Prescription>;
    investigations: string;
    chiefComplaint: string;
}): {
    id: string;
    pastHistory: string;
    patientId: string;
    year: bigint;
    personalHistory: string;
    physicalGenerals: string;
    history: string;
    examination: string;
    totality: string;
    miasmaticAnalysis: string;
    mentalGenerals: string;
    familyHistory: string;
    followUps: Array<_FollowUp>;
    repertoiralFindings: string;
    prescriptions: Array<_Prescription>;
    investigations: string;
    chiefComplaint: string;
} {
    return {
        id: value.id,
        pastHistory: value.pastHistory,
        patientId: value.patientId,
        year: value.year,
        personalHistory: value.personalHistory,
        physicalGenerals: value.physicalGenerals,
        history: value.history,
        examination: value.examination,
        totality: value.totality,
        miasmaticAnalysis: value.miasmaticAnalysis,
        mentalGenerals: value.mentalGenerals,
        familyHistory: value.familyHistory,
        followUps: to_candid_vec_n5(_uploadFile, _downloadFile, value.followUps),
        repertoiralFindings: value.repertoiralFindings,
        prescriptions: value.prescriptions,
        investigations: value.investigations,
        chiefComplaint: value.chiefComplaint
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    visitNumber: bigint;
    prescription?: Prescription;
    date: string;
    feedback: string;
    symptoms: string;
    changes: string;
    observations: string;
}): {
    visitNumber: bigint;
    prescription: [] | [_Prescription];
    date: string;
    feedback: string;
    symptoms: string;
    changes: string;
    observations: string;
} {
    return {
        visitNumber: value.visitNumber,
        prescription: value.prescription ? candid_some(value.prescription) : candid_none(),
        date: value.date,
        feedback: value.feedback,
        symptoms: value.symptoms,
        changes: value.changes,
        observations: value.observations
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FollowUp>): Array<_FollowUp> {
    return value.map((x)=>to_candid_FollowUp_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
