/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Patient {
    id: string;
    age: bigint;
    sex: string;
    occupation: string;
    contact: string;
    name: string;
    address: string;
    registrationYear: bigint;
}
export interface CaseSheet {
    id: string;
    hpi: string;
    pastHistory: string;
    patientId: string;
    createdAt: bigint;
    year: bigint;
    personalHistory: string;
    physicalGenerals: string;
    examinationFindings: string;
    totality: string;
    miasmaticAnalysis: string;
    updatedAt: bigint;
    mentalGenerals: string;
    familyHistory: string;
    repertorialFindings: string;
    investigations: string;
    chiefComplaint: string;
}
export interface Memo {
    id: string;
    content: string;
    createdAt: bigint;
}
export interface FollowUp {
    id: string;
    rows: string;
    caseSheetId: string;
}
export interface Appointment {
    id: string;
    status: string;
    date: string;
    time: string;
    patientName: string;
    reason: string;
}
export interface Prescription {
    id: string;
    rows: string;
    caseSheetId: string;
}
export interface DoctorAccount {
    username: string;
    name: string;
    createdAt: bigint;
    role: string;
    gmail: string;
    passwordHash: string;
    phone: string;
    qualification: string;
    mustChangePassword: boolean;
}
export interface UserProfile {
    name: string;
    role: string;
    specialization?: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changeOwnPassword(username: string, oldPasswordHash: string, newPasswordHash: string): Promise<string>;
    createAppointment(appointment: Appointment): Promise<string>;
    createCaseSheet(caseSheet: CaseSheet): Promise<string>;
    createDoctorWithPassword(username: string, passwordHash: string): Promise<string>;
    createFollowUp(followUp: FollowUp): Promise<string>;
    createMemo(memo: Memo): Promise<string>;
    createPatient(patient: Patient): Promise<string>;
    createPrescription(prescription: Prescription): Promise<string>;
    deleteAppointment(id: string): Promise<void>;
    deleteCaseSheet(id: string): Promise<void>;
    deleteFollowUp(id: string): Promise<void>;
    deleteMemo(id: string): Promise<void>;
    deletePatient(id: string): Promise<void>;
    deletePrescription(id: string): Promise<void>;
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllDoctorAccounts(): Promise<Array<DoctorAccount>>;
    getAllMemos(): Promise<Array<Memo>>;
    getAllPatients(): Promise<Array<Patient>>;
    getAppointment(id: string): Promise<Appointment>;
    getAppointmentsByDate(date: string): Promise<Array<Appointment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCaseSheet(id: string): Promise<CaseSheet>;
    getCaseSheetsByPatient(patientId: string): Promise<Array<CaseSheet>>;
    getFollowUp(id: string): Promise<FollowUp>;
    getFollowUpsByCaseSheet(caseSheetId: string): Promise<Array<FollowUp>>;
    getPatient(id: string): Promise<Patient>;
    getPatientsByYear(year: bigint): Promise<Array<Patient>>;
    getPrescription(id: string): Promise<Prescription>;
    getPrescriptionsByCaseSheet(caseSheetId: string): Promise<Array<Prescription>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    loginWithPassword(username: string, passwordHash: string): Promise<DoctorAccount | null>;
    registerWithPassword(username: string, passwordHash: string, name: string, qualification: string, gmail: string, phone: string): Promise<string>;
    resetDoctorPassword(username: string, newPasswordHash: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAppointment(id: string, appointment: Appointment): Promise<void>;
    updateCaseSheet(id: string, caseSheet: CaseSheet): Promise<void>;
    updateDoctorAccountRole(username: string, newRole: string): Promise<string>;
    updateFollowUp(id: string, followUp: FollowUp): Promise<void>;
    updateMemo(id: string, memo: Memo): Promise<void>;
    updatePatient(id: string, patient: Patient): Promise<void>;
    updatePrescription(id: string, prescription: Prescription): Promise<void>;
    usernameExists(username: string): Promise<boolean>;
}
import type { DoctorAccount as _DoctorAccount, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeOwnPassword(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.changeOwnPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeOwnPassword(arg0, arg1, arg2);
            return result;
        }
    }
    async createAppointment(arg0: Appointment): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(arg0);
            return result;
        }
    }
    async createCaseSheet(arg0: CaseSheet): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCaseSheet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCaseSheet(arg0);
            return result;
        }
    }
    async createDoctorWithPassword(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDoctorWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDoctorWithPassword(arg0, arg1);
            return result;
        }
    }
    async createFollowUp(arg0: FollowUp): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createFollowUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFollowUp(arg0);
            return result;
        }
    }
    async createMemo(arg0: Memo): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createMemo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMemo(arg0);
            return result;
        }
    }
    async createPatient(arg0: Patient): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatient(arg0);
            return result;
        }
    }
    async createPrescription(arg0: Prescription): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrescription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrescription(arg0);
            return result;
        }
    }
    async deleteAppointment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return result;
        }
    }
    async deleteCaseSheet(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCaseSheet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCaseSheet(arg0);
            return result;
        }
    }
    async deleteFollowUp(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFollowUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFollowUp(arg0);
            return result;
        }
    }
    async deleteMemo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMemo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMemo(arg0);
            return result;
        }
    }
    async deletePatient(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async deletePrescription(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePrescription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePrescription(arg0);
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return result;
        }
    }
    async getAllDoctorAccounts(): Promise<Array<DoctorAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoctorAccounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoctorAccounts();
            return result;
        }
    }
    async getAllMemos(): Promise<Array<Memo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMemos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMemos();
            return result;
        }
    }
    async getAllPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return result;
        }
    }
    async getAppointment(arg0: string): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return result;
        }
    }
    async getAppointmentsByDate(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByDate(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaseSheet(arg0: string): Promise<CaseSheet> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseSheet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseSheet(arg0);
            return result;
        }
    }
    async getCaseSheetsByPatient(arg0: string): Promise<Array<CaseSheet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseSheetsByPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseSheetsByPatient(arg0);
            return result;
        }
    }
    async getFollowUp(arg0: string): Promise<FollowUp> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowUp(arg0);
            return result;
        }
    }
    async getFollowUpsByCaseSheet(arg0: string): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowUpsByCaseSheet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowUpsByCaseSheet(arg0);
            return result;
        }
    }
    async getPatient(arg0: string): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return result;
        }
    }
    async getPatientsByYear(arg0: bigint): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientsByYear(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientsByYear(arg0);
            return result;
        }
    }
    async getPrescription(arg0: string): Promise<Prescription> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescription(arg0);
            return result;
        }
    }
    async getPrescriptionsByCaseSheet(arg0: string): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescriptionsByCaseSheet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescriptionsByCaseSheet(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginWithPassword(arg0: string, arg1: string): Promise<DoctorAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithPassword(arg0, arg1);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithPassword(arg0, arg1);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerWithPassword(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWithPassword(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWithPassword(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async resetDoctorPassword(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.resetDoctorPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetDoctorPassword(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAppointment(arg0: string, arg1: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointment(arg0, arg1);
            return result;
        }
    }
    async updateCaseSheet(arg0: string, arg1: CaseSheet): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCaseSheet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCaseSheet(arg0, arg1);
            return result;
        }
    }
    async updateDoctorAccountRole(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctorAccountRole(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctorAccountRole(arg0, arg1);
            return result;
        }
    }
    async updateFollowUp(arg0: string, arg1: FollowUp): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFollowUp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFollowUp(arg0, arg1);
            return result;
        }
    }
    async updateMemo(arg0: string, arg1: Memo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemo(arg0, arg1);
            return result;
        }
    }
    async updatePatient(arg0: string, arg1: Patient): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, arg1);
            return result;
        }
    }
    async updatePrescription(arg0: string, arg1: Prescription): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrescription(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrescription(arg0, arg1);
            return result;
        }
    }
    async usernameExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.usernameExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.usernameExists(arg0);
            return result;
        }
    }
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DoctorAccount]): DoctorAccount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    specialization: [] | [string];
}): {
    name: string;
    role: string;
    specialization?: string;
} {
    return {
        name: value.name,
        role: value.role,
        specialization: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.specialization))
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    specialization?: string;
}): {
    name: string;
    role: string;
    specialization: [] | [string];
} {
    return {
        name: value.name,
        role: value.role,
        specialization: value.specialization ? candid_some(value.specialization) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
